### ISSUE TITLE
Quizlet Import Issue 

### ISSUE THREAD

**Issue by RobinCate2** [kelciour/improved-quizlet-to-anki-21-importer#15]
When I import the deck I get this error code. The deck shows up on my profile, but there are no cards in the imported deck. I've checked for updates. Anyway to fix the issue?

Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-08-24 17:40:08

Caught exception:
Traceback (most recent call last):
  File "C:\Users\robin\AppData\Roaming\Anki2\addons21\538351043\__init__.py", line 369, in onCode
    self.downloadSet(url)
  File "C:\Users\robin\AppData\Roaming\Anki2\addons21\538351043\__init__.py", line 461, in downloadSet
    self.createDeck(deck, parentDeck)
  File "C:\Users\robin\AppData\Roaming\Anki2\addons21\538351043\__init__.py", line 580, in createDeck
    file_name = self.fileDownloader(term["_imageUrl"])
  File "C:\Users\robin\AppData\Roaming\Anki2\addons21\538351043\__init__.py", line 606, in fileDownloader
    with open(file_name, 'wb') as f:
PermissionError: [Errno 13] Permission denied: 'quizlet-V.ldFeD.4XpqSqlskW0Klg.png'

**Comment by cptmedic** [comment]
PR #16 should provide a quick fix for failed image downloads
