### ISSUE TITLE
Issue with Quizlet Importer on Anki

### ISSUE THREAD

**Issue by goofymoofy** [kelciour/improved-quizlet-to-anki-21-importer#22]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "C:\Users\mf150503\AppData\Roaming\Anki2\addons21\538351043\__init__.py", line 610, in runQuizletPlugin
    __window = QuizletWindow()
  File "C:\Users\mf150503\AppData\Roaming\Anki2\addons21\538351043\__init__.py", line 188, in __init__
    self.initGUI()
  File "C:\Users\mf150503\AppData\Roaming\Anki2\addons21\538351043\__init__.py", line 252, in initGUI
    self.setSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
AttributeError: type object 'QSizePolicy' has no attribute 'Minimum'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Improved Quizlet to Anki 21 Importer ['538351043', 2020-11-15T02:16, 'None', '']

===IDs of active AnkiWeb add-ons===
538351043

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by kelciour** [comment]
It's been unmaintained and it's currently broken.

Try the updated version with audio support by unchecking the Download audio checkbox - https://ankiweb.net/shared/info/1362209126
