### ISSUE TITLE
Error importing deck (lots of images, got about half way through)

### ISSUE THREAD

**Issue by michaelcward1996** [kelciour/improved-quizlet-to-anki-21-importer#6]
Error importing this deck (lots of images, got about half way through)
https://quizlet.com/567825383/dli-korean-unit-12-vocab-flash-cards/

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-02-06 11:28:34

Caught exception:
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 665, in urlopen
  File "urllib3\connectionpool.py", line 421, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3\connectionpool.py", line 416, in _make_request
  File "http\client.py", line 1322, in getresponse
  File "http\client.py", line 303, in begin
  File "http\client.py", line 264, in _read_status
  File "socket.py", line 669, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2560)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 719, in urlopen
  File "urllib3\util\retry.py", line 436, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='farm4.staticflickr.com', port=443): Max retries exceeded with url: /3057/2445139780_62c0e3f047.jpg (Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2560)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\micha\AppData\Roaming\Anki2\addons21\538351043\__init__.py", line 299, in onCode
    self.downloadSet(url, parentDeck)
  File "C:\Users\micha\AppData\Roaming\Anki2\addons21\538351043\__init__.py", line 393, in downloadSet
    self.createDeck(deck, parentDeck)
  File "C:\Users\micha\AppData\Roaming\Anki2\addons21\538351043\__init__.py", line 510, in createDeck
    file_name = self.fileDownloader(term["_imageUrl"])
  File "C:\Users\micha\AppData\Roaming\Anki2\addons21\538351043\__init__.py", line 526, in fileDownloader
    r = requests.get(url, stream=True, verify=False, headers=headers)
  File "requests\api.py", line 75, in get
  File "requests\api.py", line 60, in request
  File "requests\sessions.py", line 533, in request
  File "requests\sessions.py", line 646, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='farm4.staticflickr.com', port=443): Max retries exceeded with url: /3057/2445139780_62c0e3f047.jpg (Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2560)')))

**Comment by kelciour** [comment]
Maybe it's a network issue. Maybe just try to import the same set again. If a VPN was installed and working, maybe try to turn it off.
