### ISSUE TITLE
HTTP Error 403

### ISSUE THREAD

**Issue by captainamirica** [kelciour/improved-quizlet-to-anki-21-importer#8]
when you are trying to add any decks, it will show this and the captcha option doesn't work with any of them because they're not private. Please fix this as my livelihood in school depends on this importer. 

Debug info:
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: MacOS 11.2.3
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-06-12 16:07:23

Caught exception:
Traceback (most recent call last):
File "C:\Users\david\AppData\Roaming\Anki2\addons21\538351043\__init__.py", line 350, in onCode
r.raise_for_status()
File "requests\models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 403

**Comment by kelciour** [comment]
It's being protected by Cloudflare and it's unlikely I'll do something about it.

![изображение](https://user-images.githubusercontent.com/16260735/123872836-4b551900-d93e-11eb-822e-fb4daaf1630f.png)

As a possible workaround, if there no problem to download a single Quizlet set without triggering a captcha challenge, open DevTools, switch to the Console panel, copy-paste the following code and press Enter to run it. Then select and copy all Quizlet urls and add them to the add-on as Quizlet URL. The add-on will download all of them one by one.

```
sets = [];
document.querySelectorAll('.UISetCard').forEach(card => {
  url = card.querySelector('a')['href'];
  sets.push(url);
});
sets = sets.join('\n');
console.log(sets);
```

![изображение](https://user-images.githubusercontent.com/16260735/123872823-44c6a180-d93e-11eb-9447-93ebf82ab3e0.png)
