### ISSUE TITLE
Error while importing Quizlet folders

### ISSUE THREAD

**Issue by stephenpasquini** [kelciour/improved-quizlet-to-anki-21-importer#9]
Thank you so much for creating this importer. It's terrific for importing single decks, but I cannot seem to bulk import from Quizlet folders. I have been trying to import this folder to Anki, but I keep getting an error message: https://quizlet.com/SmartyPANCE/folders/pance-eent-7-nccpa-content-blueprint-study-guide-smarty-pance/sets

![image](https://user-images.githubusercontent.com/16261419/143776204-a1c3759f-84ba-4fb1-a83a-be965b1d638d.png)

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-11-28 07:57:09
Add-ons possibly involved: ⁨Improved Quizlet to Anki 21 Importer⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/stephenpasquini/Library/Application Support/Anki2/addons21/538351043/__init__.py", line 305, in onCode
    r.raise_for_status()
  File "requests/models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://quizlet.com/SmartyPANCE/folders/pance-eent-7-nccpa-content-blueprint-study-guide-smarty-pance?x=1xqt&i=24e7wo

Any help would be very much appreciated.

Thanks for your time in putting this together!!

Stephen

**Comment by kelciour** [comment]
It's unlikely it will be fixed by me, at least to make it invisible to the user. A possible alternative is to show the captcha and ask the user to solve it or maybe write a simple Chrome extension to import cards using AnkiConnect, but I'm not interested to do it anytime soon.

I can only suggest to install this version - https://github.com/kelciour/improved-quizlet-to-anki-21-importer/releases/tag/v1.2.3-captcha - as it appears to be still working and can import your folder just fine - https://siasky.net/AACGxGZhnLNb2317MlIrkQ1ZWQHaeZYytqMLX06R6__V2w

**Comment by stephenpasquini** [comment]
Thanks a million!! This worked like a charm. Truly thankful. 

Stephen
